

export const segments = [
    {
        name:"ENT_CompanyName",
        rules:["ENT_CompanyName1"],
        operator:"all"
    },
    {
        name:"Ortho_CompanyNameExperience",
        rules:["Ortho_CompanyNameExperience1"],
        operator:"all"
    },
    {
        name:"gTelehealth-abm",
        rules:["gTelehealth-abm1"],
        operator:"all"
    },
    {
        name:"Gastro_CompanyName1",
        rules:["Gastro_CompanyName11"],
        operator:"all"
    },
    {
        name:"redtest-derm",
        rules:["redtest-derm1"],
        operator:"all"
    },
    {
        name:"Dermatologysuite",
        rules:["Dermatologysuite1"],
        operator:"all"
    },
    {
        name:"Gastroenterologysuite",
        rules:["Gastroenterologysuite1"],
        operator:"all"
    },
    {
        name:"Ophthalmologysuite",
        rules:["Ophthalmologysuite1"],
        operator:"all"
    },
    {
        name:"Ophthalmologysuitevar",
        rules:["Ophthalmologysuitevar1"],
        operator:"all"
    },
    {
        name:"Orthopedicssuite",
        rules:["Orthopedicssuite1"],
        operator:"all"
    },
    {
        name:"Otolaryngologysuite",
        rules:["Otolaryngologysuite1"],
        operator:"all"
    },
    {
        name:"PainManagementsuite",
        rules:["PainManagementsuite1"],
        operator:"all"
    },
    {
        name:"PlasticSurgerysuite",
        rules:["PlasticSurgerysuite1"],
        operator:"all"
    },
    {
        name:"Dermatologysuitevar",
        rules:["Dermatologysuitevar1"],
        operator:"all"
    },
    {
        name:"Homepage",
        rules:["Homepage1"],
        operator:"all"
    },
    {
        name:"LPSwitchingDerm",
        rules:["LPSwitchingDerm1"],
        operator:"all"
    },
    {
        name:"LPSwitchingENT",
        rules:["LPSwitchingENT1"],
        operator:"all"
    },
    {
        name:"LPSwitchingGastro",
        rules:["LPSwitchingGastro1"],
        operator:"all"
    },
    {
        name:"LPSwitchingOphth",
        rules:["LPSwitchingOphth1"],
        operator:"all"
    },
    {
        name:"LPSwitchingOrtho",
        rules:["LPSwitchingOrtho1"],
        operator:"all"
    },
    {
        name:"LPSwitchingPlastics",
        rules:["LPSwitchingPlastics1"],
        operator:"all"
    },
    {
        name:"LPSwitchingGeneral",
        rules:["LPSwitchingGeneral1"],
        operator:"all"
    },
    {
        name:"LPBoostfinancialhealth",
        rules:["LPBoostfinancialhealth1"],
        operator:"all"
    },
    {
        name:"LPGIBoostfinancialhealth",
        rules:["LPGIBoostfinancialhealth1"],
        operator:"all"
    },
    {
        name:"LPGastroE/MIQquiz",
        rules:["LPGastroE/MIQquiz1"],
        operator:"all"
    },
    {
        name:"LPE/MIQquiz",
        rules:["LPE/MIQquiz1"],
        operator:"all"
    },
    {
        name:"LPSwitchingPain",
        rules:["LPSwitchingPain1"],
        operator:"all"
    },
    {
        name:"LPNextechPracticeEfficiency",
        rules:["LPNextechPracticeEfficiency1"],
        operator:"all"
    },
    {
        name:"LPE/MIQquizvar",
        rules:["LPE/MIQquizvar1"],
        operator:"all"
    },
    {
        name:"LPGastroE/MIQquizvar",
        rules:["LPGastroE/MIQquizvar1"],
        operator:"all"
    },
    {
        name:"LPENTCustomerSupport",
        rules:["LPENTCustomerSupport1"],
        operator:"all"
    },
    {
        name:"LPENTCustomerSupportvar",
        rules:["LPENTCustomerSupportvar1"],
        operator:"all"
    },
    {
        name:"LPbundledsolutions",
        rules:["LPbundledsolutions1"],
        operator:"all"
    },
    {
        name:"LPPremiumPatientConnect",
        rules:["LPPremiumPatientConnect1"],
        operator:"all"
    },
    {
        name:"LPOpticalInventory",
        rules:["LPOpticalInventory1"],
        operator:"all"
    },
    {
        name:"LPDermcloudvsonpremise",
        rules:["LPDermcloudvsonpremise1"],
        operator:"all"
    },
    {
        name:"LPPlasticcloudvson-premise",
        rules:["LPPlasticcloudvson-premise1"],
        operator:"all"
    },
    {
        name:"LPOrthocloudvson-premise",
        rules:["LPOrthocloudvson-premise1"],
        operator:"all"
    },
    {
        name:"LPenterprise360-ortho",
        rules:["LPenterprise360-ortho1"],
        operator:"all"
    },
    {
        name:"LPenterprise360",
        rules:["LPenterprise3601"],
        operator:"all"
    },
    {
        name:"LPPatientSelf-Scheduling",
        rules:["LPPatientSelf-Scheduling1"],
        operator:"all"
    },
    {
        name:"LPGastroassessment",
        rules:["LPGastroassessment1"],
        operator:"all"
    },
    {
        name:"LPGastroassessmentvariation",
        rules:["LPGastroassessmentvariation1"],
        operator:"all"
    },
    {
        name:"LPGastroTrust",
        rules:["LPGastroTrust1"],
        operator:"all"
    },
    {
        name:"LPHandSurgeonsSwitch",
        rules:["LPHandSurgeonsSwitch1"],
        operator:"all"
    },
    {
        name:"LPSolutionsRenewal",
        rules:["LPSolutionsRenewal1"],
        operator:"all"
    },
    {
        name:"LPGastroCloudConversion",
        rules:["LPGastroCloudConversion1"],
        operator:"all"
    },
    {
        name:"LPEMAKiosk",
        rules:["LPEMAKiosk1"],
        operator:"all"
    },
    {
        name:"LPgKiosk",
        rules:["LPgKiosk1"],
        operator:"all"
    },
    {
        name:"LPMIPSmadness",
        rules:["LPMIPSmadness1"],
        operator:"all"
    },
    {
        name:"LPSwitchingDermrebootvar",
        rules:["LPSwitchingDermrebootvar1"],
        operator:"all"
    },
    {
        name:"LPlearnmoredermatology",
        rules:["LPlearnmoredermatology1"],
        operator:"all"
    },
    {
        name:"LPlearnmoredermatologytimed",
        rules:["LPlearnmoredermatologytimed1"],
        operator:"all"
    },
    {
        name:"LPlearnmoredermatologyexit",
        rules:["LPlearnmoredermatologyexit1"],
        operator:"all"
    },
    {
        name:"LPGIMIPSmadness",
        rules:["LPGIMIPSmadness1"],
        operator:"all"
    },
    {
        name:"LPGastroreturn-to-careassessment",
        rules:["LPGastroreturn-to-careassessment1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMoreENT",
        rules:["LPSwitchingLearnMoreENT1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMoreENTtimed",
        rules:["LPSwitchingLearnMoreENTtimed1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMoreENTexit",
        rules:["LPSwitchingLearnMoreENTexit1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMoreOrtho",
        rules:["LPSwitchingLearnMoreOrtho1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMoreOrthotimed",
        rules:["LPSwitchingLearnMoreOrthotimed1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMoreOrthoexit",
        rules:["LPSwitchingLearnMoreOrthoexit1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMoreOphth",
        rules:["LPSwitchingLearnMoreOphth1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMoreOphthtimed",
        rules:["LPSwitchingLearnMoreOphthtimed1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMoreOphthexit",
        rules:["LPSwitchingLearnMoreOphthexit1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMorePain",
        rules:["LPSwitchingLearnMorePain1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMorePaintimed",
        rules:["LPSwitchingLearnMorePaintimed1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMorePainexit",
        rules:["LPSwitchingLearnMorePainexit1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMorePlastic",
        rules:["LPSwitchingLearnMorePlastic1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMorePlastictimed",
        rules:["LPSwitchingLearnMorePlastictimed1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMorePlasticexit",
        rules:["LPSwitchingLearnMorePlasticexit1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMoreGastro",
        rules:["LPSwitchingLearnMoreGastro1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMoreGastrotimed",
        rules:["LPSwitchingLearnMoreGastrotimed1"],
        operator:"all"
    },
    {
        name:"LPSwitchingLearnMoreGastroexit",
        rules:["LPSwitchingLearnMoreGastroexit1"],
        operator:"all"
    },
    {
        name:"LPSwitchingENTrebootvar",
        rules:["LPSwitchingENTrebootvar1"],
        operator:"all"
    },
    {
        name:"LPSwitchingGastrorebootvar",
        rules:["LPSwitchingGastrorebootvar1"],
        operator:"all"
    },
    {
        name:"LPSwitchingOphthrebootvar",
        rules:["LPSwitchingOphthrebootvar1"],
        operator:"all"
    },
    {
        name:"LPSwitchingOrthorebootvar",
        rules:["LPSwitchingOrthorebootvar1"],
        operator:"all"
    },
    {
        name:"LPSwitchingPainrebootvar",
        rules:["LPSwitchingPainrebootvar1"],
        operator:"all"
    },
    {
        name:"LPSwitchingPlasticrebootvar",
        rules:["LPSwitchingPlasticrebootvar1"],
        operator:"all"
    },
    {
        name:"LPEMAVBC",
        rules:["LPEMAVBC1"],
        operator:"all"
    },
    {
        name:"LPPatientPortal",
        rules:["LPPatientPortal1"],
        operator:"all"
    },
    {
        name:"LPGastroPatientPortal",
        rules:["LPGastroPatientPortal1"],
        operator:"all"
    },
    {
        name:"LPgAdvisor",
        rules:["LPgAdvisor1"],
        operator:"all"
    },
    {
        name:"LPUrologyLaunch",
        rules:["LPUrologyLaunch1"],
        operator:"all"
    },
    {
        name:"LPMIPSquiz",
        rules:["LPMIPSquiz1"],
        operator:"all"
    },
    {
        name:"LPDermassessment",
        rules:["LPDermassessment1"],
        operator:"all"
    },
    {
        name:"LPPlasticassessment",
        rules:["LPPlasticassessment1"],
        operator:"all"
    },
    {
        name:"LPENTCOSMVirtual",
        rules:["LPENTCOSMVirtual1"],
        operator:"all"
    },
    {
        name:"LPGIVBC",
        rules:["LPGIVBC1"],
        operator:"all"
    },
    {
        name:"LPEMAAppointmentCommunications",
        rules:["LPEMAAppointmentCommunications1"],
        operator:"all"
    },
    {
        name:"LPGIAppointmentCommunications",
        rules:["LPGIAppointmentCommunications1"],
        operator:"all"
    },
    {
        name:"LPUrologysuite",
        rules:["LPUrologysuite1"],
        operator:"all"
    },
    {
        name:"LPPodiatrysuite",
        rules:["LPPodiatrysuite1"],
        operator:"all"
    },

    {
        name:"LPAAPM2021",
        rules:["LPAAPM20211"],
        operator:"all"
    },

    {
        name:"LPENTPAC",
        rules:["LPENTPAC1"],
        operator:"all"
    },
    {
        name:"LPDermassessmentvar",
        rules:["LPDermassessmentvar1"],
        operator:"all"
    },
    {
        name:"LPPlasticassessmentvar",
        rules:["LPPlasticassessmentvar1"],
        operator:"all"
    },
    {
        name:"LPENTKeyAccount",
        rules:["LPENTKeyAccount1"],
        operator:"all"
    }

];
